### ISSUE TITLE
Afficher correctement les demande reçues “archivées” par d’autres

### ISSUE THREAD

**Issue by n-b** [betagouv/conseillers-entreprises#1323]
@stephreso:
> des besoins non pris en charge ou pris en charge mais pas clôturés, se retrouvent dans "mes demandes archivés" sans raison (ou parce qu'ils ont été clôturés par quelqu'un d'autre) : https://place-des-entreprises.beta.gouv.fr/besoins/4561

Le besoin en question a été mis en relation avec plusieurs personnes; le référent de la BDF l’a pris en charge et clôturé, et les autres (par exemple, une personne de la CCI) ne le voient plus dans les demandes reçues (`/besoins`) mais dans les demandes archivées (`/besoins/archives`). Cette notion d’archive n’est pas la même que celle des besoins archivés en base (`Need#is_archived`), mais est automatique quand un autre référent clôture le besoin.

Par ailleurs, dans les demandes archivées on a encore un onglet “Demandes Marquées en échec. On a oublié de nettoyer ça dans #1291.

Il faut
* clarifier les onglets qu’on veut avoir et
* retirer la notion de “mis en échec” et n’utiliser “archivés” que pour cela

**Comment by clairezed** [comment]
Je pense voir un lien avec #1417

**Comment by n-b** [comment]
yep, c’est exactement le même problème. Je ferme l’autre, j’ai commencé à référencer celui-ci.

**Comment by n-b** [comment]
Alors en fait, c’est deux problèmes différents. Je réouvre #1417.
