### ISSUE TITLE
Améliorer le mail d'invitation

### ISSUE THREAD

**Issue by n-b** [betagouv/conseillers-entreprises#1437]
- il manque le paragraphe « C’est un nouveau service public … »
- il faut enlever la phrase sous le bouton « si vous ne souhaitez pas accepter l’invitation… »
- changer le CTA : Choisir mon mot de passe 

https://docs.google.com/document/d/1YcnvlqY3fA2bp5_hbuFl0WfjHLOSElhzrLvg5SVlg5U/edit

**Comment by clairezed** [comment]
Voilà ce que ça donne @Adeline-Lrn @Tibo-aplus 

![Screenshot from 2020-12-07 15-03-06](https://user-images.githubusercontent.com/2668217/101360023-5dd20d00-389d-11eb-89d0-14af1e2e4718.png)

**Comment by Adeline-Lrn** [comment]
C'est super comme ça ! Il y a une phrase - que j'ai oubliée - à modifier maintenant qu'on embarque les interco, collectivités etc : 
« Il permet aux chefs d'entreprises d'être mis en relation avec le bon expert au sein des administrations, organismes publics et parapublics, et collectivités territoriales partenaires ». 

+ la phrase « vous êtes invités à rejoindre.... au sein de l'antenne XXX », on peut la passer en gras comme c'est le message essentiel à faire passer :)

**Comment by clairezed** [comment]
On oublie "...au sein des administrations, organismes publics et parapublics, et collectivités territoriales partenaires **chargés de les accompagner**" ?

**Comment by Adeline-Lrn** [comment]
J'ai remplacé par « partenaires » à la fin pour que la phrase reste digeste ^^
