### ISSUE TITLE
Mettre les numéros du support dans le mail de notification

### ISSUE THREAD

**Issue by n-b** [betagouv/conseillers-entreprises#1438]
Mettre numéro de tel de Tibo et steph dans le mail de notification du besoin à l'expert :
« Si vous n'arrivez pas à accéder à la fiche entreprise, appelez : 
- en Ile-de-France, Thibault Desjardin – 06 22 99 03 65 –thibault.desjardins@beta.gouv.fr ; 
- en Hauts-de-France, Stéphanie Denysenko – 06 33 56 60 00 – stephanie.denysenko@beta.gouv.fr ».

**Comment by clairezed** [comment]
ici, je vois plusieurs mails possibles : 

- first_notification_help
- notify_company_needs_from_partner
- notify_company_needs_with_solicitation
- notify_company_needs_without_solicitation

C'est pour tous, qu'il faut rajouter la mention ?

**Comment by clairezed** [comment]
Ah, y'a peut-être plusieurs mailer_preview, mais un seul mailer, en fait ?

**Comment by clairezed** [comment]
@Adeline-Lrn @Tibo-aplus @stephreso voilà ce que ça donnerait (tel et mail cliquables) : 
![Screenshot from 2020-12-07 16-27-23](https://user-images.githubusercontent.com/2668217/101369956-2ff2c580-38a9-11eb-933b-92bd4c96174a.png)

**Comment by Adeline-Lrn** [comment]
L'encart orange prête à confusion j'ai l'impression, ils sont censé avoir reçu le mail d'activation avant les sollicitations. 

Peut-être l'afficher que pour la 1ère notification (contrairement aux coordonnées qui restent) : 

Attention ! Place des Entreprises nécessite de se connecter à son compte utilisateur pour accéder aux informations des entreprises. Vous avez dû recevoir un mail pour activer votre compte et choisir votre de mot de passe.

**Comment by clairezed** [comment]
@Adeline-Lrn l'encart orange n'est présent que si l'expert n'a jamais utilisé son compte, auquel cas un email expliquant comment activer son compte lui est automatiquement envoyé. 
J'ai fait en sorte que l'encart soit affiché sur la capture d'écran pour prendre en compte ce cas de figure dans le design de l'email :)

Les contacts support, eux, sont bien affichés à chaque fois.

**Comment by Adeline-Lrn** [comment]
Ahh super, je n'avais pas en tête cette amélioration supplémentaire avec les instructions qui repartent automatiquement ! C'est génial alors !

**Comment by clairezed** [comment]
rendons à César, etc : c'est pas moi ça, hein, c'était là avant !
