### ISSUE TITLE
Chantier gestion des iframes (fin)

### ISSUE THREAD

**Issue by clairezed** [betagouv/conseillers-entreprises#3583]
- [x] Possibilité de supprimer définitivement les sujets archivés qui n'ont pas de sollicitation (ménage après projet de création n'ayant pas abouti) Ex : https://conseillers-entreprises.service-public.fr/admin/subjects?q%5Btheme_id_eq%5D=20&scope=is_archived
- [x] #3586
- [x] #3587
- [ ] #3584

Lien vers les post-it Miro : https://trello.com/c/DE4VAzfo/734-enjeux-iframe

--- 
Deux distinctions à faire dans les landings : 
- landings avec des sujets spécifiques, personnalisés (= ne figurant pas de base sur CE)
- landings avec des sujets territorialisés (seul des experts dans un territoire précis sont compétents sur ces sujets)

Exemples de combinaisons : 

- **national et sujets classique RH** : [rh-mon-entreprise-urssaf-fr](https://conseillers-entreprises.service-public.fr/admin/landings/rh-mon-entreprise-urssaf-fr)
  - rien de particulier
- **national et que des sujets personnalisés** : [espace-fournisseurs](https://conseillers-entreprises.service-public.fr/admin/landings/espace-fournisseurs)
  - les besoins déposés sur ces sujets apparaissent sous l'agglomérat "Coopération" dans le graphique "par thème" des stats
  - on fait apparaître d'une façon ou d'une autre en admin qu'il y a des sujets spécifiques ?
- **national et mixte sujets classiques et sujets personnalisés** (pas encore en ligne) : [portail-des-travailleurs-independants-handicapes](https://conseillers-entreprises.service-public.fr/admin/landings/portail-des-travailleurs-independants-handicapes)
  - les besoins déposés sur les sujets personnalisés apparaissent sous l'agglomérat "Coopération" dans le graphique "par thème" des stats
  - on fait apparaître d'une façon ou d'une autre en admin qu'il y a des sujets spécifiques ?
- **régional et sujets classiques** : [zetwal](https://conseillers-entreprises.service-public.fr/admin/landings/zetwal)
  - rien de particulier
- **régional et que des sujets personnalisés** : [espace-organisme-formation-dreets-aura](https://conseillers-entreprises.service-public.fr/admin/landings/espace-organisme-formation-dreets-aura)
    - les besoins déposés sur les sujets personnalisés apparaissent sous l'agglomérat "Coopération" dans le graphique "par thème" des stats
    - on fait apparaître d'une façon ou d'une autre en admin qu'il y a des sujets spécifiques ?
    - on fait apparaître en admin qu'il y a des sujets régionaux (et quelle région ça concerne)
    - on ne fait apparaître dans l'annuaire d'éventuels trous que dans la région concernée
- **régional et mixte sujets classiques et sujets personnalisés** : [team-rh-occitanie](https://conseillers-entreprises.service-public.fr/admin/landings/team-rh-occitanie)
    - les besoins déposés sur les sujets personnalisés apparaissent sous l'agglomérat "Coopération" dans le graphique "par thème" des stats
    - on fait apparaître d'une façon ou d'une autre en admin qu'il y a des sujets spécifiques ?
    - on fait apparaître en admin qu'il y a des sujets régionaux (et quelle région ça concerne)
    - on ne fait apparaître dans l'annuaire d'éventuels trous que dans la région

**Comment by clairezed** [comment]
Coopération = toutes les iframes ? Et les API ? Certaines landing (iframe + api) ?

    Un besoin qui vient de la coopération : 
    - sujet lié à un thème propre à une coopération ?
    - besoin lié à une landing coopération ?

    Un expert qui vient de la coopération = ????

**Comment by Adeline-Lrn** [comment]
Mémo pour l'objet coopération :
- notion de coopération utile pour la gestion des logos plutôt qu'au niveau de l'iframe basé sur nos institutions (ex : Team RH, les entreprises s'engagent, futur site TIH qui sont des entités à part, avec plusieurs iframes potentiellement) ; 
- notion de coopération utile pour faire des graph d'acquisition cad la répartition des besoins détectés entre les différentes coopérations (se représenter visuellement l'importance de ces coopérations dans notre acquisition de besoins, regrouper les iframes appartenant à une même coopération pour éviter l'éventail de catégories ?)
