### ISSUE TITLE
bug lors de l'envoie d'invitation après création d'utilisateurs

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/conseillers-entreprises#3635]
Parfois les utilisateur ne se voient pas attribuer d'invitation_token alors qu'une invitation a été envoyé

Apparemment ça ne le faisait pas avant https://github.com/betagouv/conseillers-entreprises/pull/3604/files

arrive fréquemment en utilisant les actions groupé pour envoyer les invitations

**Comment by clairezed** [comment]
Ce n'est pas un bug, c'était une mauvaise manip
