### ISSUE TITLE
Bandeau séquence mails personnalisés avec visage et coordonnée  + fiche entreprise quand on clique sur le référent (maquette figma)

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/conseillers-entreprises#3714]
https://www.figma.com/design/FdReB9DP1vfC4C76egdmN5/Conseillers-Entreprises?node-id=0-1&node-type=canvas

Le modèle retenu dans la version 2 : le bandeau gris aligné à gauche 

- Pour le mail poussin, mail de relance d'un stock et mails de la dernière chance qui sont personnalisés en monde envoi direct du référent, variante du titre : 
« Pour toute question, contactez-moi »

- Pour le mail stats, quand ce sont les responsables nationaux (donc pas par région), c'est Mathieu

**Comment by Adeline-Lrn** [comment]
Doc avec la séquence mails pour la vue d'ensemble et les 2 catégories : mail institutionnel et mail plus direct 
https://docs.google.com/document/d/1xTGv5EM4ps4LJlJ-4I-HL02z9FPLjD_0l3rKxd3wvbk/edit?tab=t.0

**Comment by LucienMLD** [comment]
- [ ] supprimer la partial du footer
